<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>7.3</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>QuanLyHeThong</AssemblyName>
    <Product>Quản Lý Hệ Thống</Product>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0.0</FileVersion>
    <Platforms>AnyCPU</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!-- Assembly khung của .NET Framework (WMI) -->
    <Reference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <!-- Cho phép build .NET Framework 4.7.2 trên máy CI của GitHub -->
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
